project_name: apictl
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
release:
  github:
    owner: humanlogio
    name: apictl
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    # hooks:
    #   after: echo {{ .Path }} {{ .Major }} {{ .Minor }} {{ .Patch }} {{ .Prerelease }} {{ .ShortCommit }} {{ .ReleaseURL }}
checksum:
  name_template: "checksums.txt"
# signs:
#   - cmd: gpg
#     args:
#       [
#         "-u",
#         "AAC9300A41CCE12B",
#         "--output",
#         "${signature}",
#         "--detach-sign",
#         "${artifact}",
#       ]
#     artifacts: all
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
