name: Create a prod release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create_a_release:
    name: create a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.23"
          cache: true
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config .goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${GITHUB_WORKSPACE}/dist/apictl_linux_amd64_v1" >> $GITHUB_PATH
      - run: apictl ${{ inputs.command }}
        env:
          HMAC_KEY_ID: ${{ secrets.PROD_HMAC_KEY_ID }}
          HMAC_PRIVATE_KEY: ${{ secrets.PROD_HMAC_PRIVATE_KEY }}
      - run: ./script/create_version_artifacts.sh
        env:
          CHANNEL: "main"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_URL: "https://api.humanlog.io"
          HMAC_KEY_ID: ${{ secrets.PROD_HMAC_KEY_ID }}
          HMAC_PRIVATE_KEY: ${{ secrets.PROD_HMAC_PRIVATE_KEY }}
