name: Create a dev release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create_a_dev_release:
    name: create a dev release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.23"
          cache: true
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --draft --skip validate --config .goreleaser-dev.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_BINARIES_BUCKET_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_BINARIES_BUCKET_ACCESS_KEY }}

      - run: cat ${GITHUB_WORKSPACE}/dist/metadata.json
      - run: cat ${GITHUB_WORKSPACE}/dist/artifacts.json
      - run: echo "${GITHUB_WORKSPACE}/dist/apictl_linux_amd64_v1" >> $GITHUB_PATH
      - run: apictl ${{ inputs.command }}
        env:
          HMAC_KEY_ID: ${{ secrets.DEV_HMAC_KEY_ID }}
          HMAC_PRIVATE_KEY: ${{ secrets.DEV_HMAC_PRIVATE_KEY }}
      - run: ./script/create_version_artifacts.sh
        env:
          CHANNEL: "dev"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_URL: "https://api.humanlog.dev"
          HMAC_KEY_ID: ${{ secrets.DEV_HMAC_KEY_ID }}
          HMAC_PRIVATE_KEY: ${{ secrets.DEV_HMAC_PRIVATE_KEY }}
