on:
  workflow_dispatch
jobs:
  create_a_release:
    name: create a release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: wget -O - https://github.com/humanlogio/apictl/releases/download/0.1.0/apictl_0.1.0_Linux_x86_64.tar.gz | tar xz
    - run: ./apictl --help
    
