name: Create a release
on:
  push:
    tags: [*]

permissions:
  contents: write

jobs:
  create_a_release:
    name: create a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.4"
          cache: true
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: List keys
        run: gpg -K
      - run: wget -O - https://github.com/humanlogio/apictl/releases/download/0.1.0/apictl_0.1.0_Linux_x86_64.tar.gz | tar xz
      - run: ./apictl ${{ inputs.command }}
        env:
          HMAC_KEY_ID: ${{ secrets.HMAC_KEY_ID }}
          HMAC_PRIVATE_KEY: ${{ secrets.HMAC_PRIVATE_KEY }}
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
